### PR TITLE
Tidy up

### PR DESCRIPTION
**Pull request by neftaly**
A bunch of small changes, mostly stylistic.
The only notable change is that unknown resource types will generate an attribute, not an element.

### CODE REVIEW

**Comment by neftaly** [comment]
@fmarier

**Comment by fmarier** [comment]
I like how it's broken down, very easy to review.

It looks good, but I think we should hold off on returning null for unknown mime types. Let's take that commit out and create an issue for it and then we can discuss what our options are.

**Comment by neftaly** [comment]
Cool, mind if I also add a commit swapping JSHint for [JSCS](http://jscs.info/)? I'll keep the rules the same, and you won't have to stay up every night dreading the day I decide to make a JSLint PR :P

**Comment by fmarier** [comment]
On 23/02/15 13:50, Neftaly Hernandez wrote:
> Cool, mind if I also add a commit swapping JSHint for JSCS
> <http://jscs.info/>?

Can you do that in a separate branch and PR? I haven't looked at JSCS
yet and I don't want that to hold up your other fixes.

**Comment by neftaly** [comment]
@fmarier

**Pull request merged**
