### PR TITLE
Tweak security headers.

### PR DESCRIPTION
**Pull request by XhmikosR**
Specify HSTS preload.
Also, explicitly set the default ones.

Next step would be to make sure we comply with the HSTS preload list requirements and submit the URL https://hstspreload.appspot.com/

### CODE REVIEW

**Comment by fmarier** [comment]
> +      noSniff: true,
> +      noOpen: true,
> +      xss: true

These are all already enabled since they are ON by default. I think we can leave them out of the config.

For HSTS, I think the default value (15768000) is sufficient. I do however like the fact that you added the `includeSubDomains`, let's do that for sure.

On the preload side, I think we should only add that once we're ready to apply for it. Right now, we don't comply with these requirements:

- Redirect all HTTP traffic to HTTPS—i.e. be HTTPS only.
- If you are serving an additional redirect from your HTTPS site, that redirect must still have the HSTS header (not the page it redirects to).

**Comment by XhmikosR** [comment]
I went for this duration since this is what I personally use. I can change it of course if you prefer that.

I also prefer to explicitly set what I want to be set rather than not knowing what is enabled or might change in a lib update. The final call is again yours.

About the rest. I'd say, we better fix the redirect issue once and for all and then merge this.

**Comment by fmarier** [comment]
> I went for this duration since this is what I personally use. I can change it of course if you prefer that.
> I also prefer to explicitly set what I want to be set rather than not knowing what is enabled or might change in a lib update. The final call is again yours.

I could be swayed, but in this case, the defaults are pretty good and I'd be tempted to just use them and have one less thing to maintain in our codebase.

> About the rest. I'd say, we better fix the redirect issue once and for all and then merge this.

I think it's still worthwhile to merge the `includeSubDomains` bit. Fixing the redirects is going to require figuring out what's wrong with the Heroku config, so I'm honestly not sure when that's going to happen.

**Comment by XhmikosR** [comment]
@fmarier: I'd rather be explicit than having to follow what the defaults of hapi can be.

That being said, feel free to close it if you don't want to merge this as is.

**Comment by fmarier** [comment]
I will close this since we  should be able to rely on the defaults for now.

**Pull request closed without merging**
