### PR TITLE
Update resourceTypes to conform with WHATWG spec

### PR DESCRIPTION
**Pull request by neftaly**

### CODE REVIEW

**Comment by neftaly** [comment]
@fmarier

**Comment by fmarier** [comment]
I wonder why Travis is stuck...

**Comment by neftaly** [comment]
I think they'd do really well off a button that created a micro-transaction and jumped the build queue.

**Comment by fmarier** [comment]
Think for doing this in two steps / commits.

**Comment by fmarier** [comment]
While the unit tests pass, my manual test failed: putting in `mozilla.org/humans.txt` returned a script tag and a warning.

I would expect an error and no script tag given that `text/plain` is a forbidden content-type for scripts.

**Comment by neftaly** [comment]
Hmm. My hypothesis is that the problem is `"content-type: text/plain" !== "content-type: text/plain; encoding: utf8"`.

Rather than duplicating code from #38, I think I'm going to have to make neftaly/sri-toolbox output a JS object, then make mozilla/srihash.org use the filtered `content-type` property.
```js
{
    integrity: "xxxx",
    sha256: "xxxx",
    "content-type": "xxxx"
    ... etc
}
```
It's a breaking change, but it looks like the build tools will also require this data.

**Comment by neftaly** [comment]
@fmarier 
Help! I fixed the problem but messed up the merge (I think?)

**Comment by neftaly** [comment]
@fmarier 
Ok, it should be fixed. 

PS: I originally merged with origin/master instead of rebasing, and screwed everything up, but it's all fine now.

**Comment by fmarier** [comment]
Good stuff!

**Comment by neftaly** [comment]
Cheers. Still need to sort out a network testing strategy, eh!

**Pull request merged**
