### PR TITLE
Switch to Node.js 10.x and update dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @fmarier

### CODE REVIEW

**Comment by fmarier** [comment]
I updated some of the dependencies in #201. For this repo, let's stick to LTS versions of libraries. That will reduce the maintenance burden.

**Comment by MatthewHerbst** [comment]
> let's stick to LTS versions of libraries

For the record, Node 10 is not LTS yet.

**Comment by XhmikosR** [comment]
As you wish. I don't use 8.x due to the old npm, so don't expect any rebases for my PRs or any new patches until you change this decision.

**Comment by MatthewHerbst** [comment]
@XhmikosR you can easily install the new npm on node 8 with `npm install -g npm@6.2.0`

**Comment by XhmikosR** [comment]
1. I'm on Windows and 2. I don't see why I have to go out my way for this.

**Pull request closed without merging**
