### PR TITLE
Display an error when checking non-CORS resources (fix #61)

### LINKED ISSUE #61: Check for the presence of CORS headers
Now that CORS is required for cross-origin requests, we should issue a warning when it's not there.

It shouldn't be an error because maybe the author will be loading that resource over the same origin, even though that's less likely.

There are three possibilities:

1. `Access-Control-Allow-Origin: *`: open to everyone, no warning.
2. `Access-Control-Allow-Origin: example.com`: only works if loaded from `example.com` or `example.net`, we should include those in the warning (after sanitizing them of course)
3. No `Access-Control-Allow-Origin` header: warning that CORS is required for cross-origin loads

I can't find good examples for the second one though, so maybe we should tackle 1 and 3 for now.

### PR DESCRIPTION
**Pull request by fmarier**
You should merge #62 and #63 before this one.

### CODE REVIEW

**Comment by fmarier** [comment]
Note: I changed my mind and decided to display an error instead of a warning for now.

The use case for same-origin is very weak and we have some CORS evangelism to do, so we may as well encourage people to turn it on :)

**Comment by fmarier** [comment]
@neftaly are you able to take a look at these patches tomorrow? I'd like to deploy and test these fixes before the weekend if possible. Thanks!

**Comment by neftaly** [comment]
Sure, will check it out before lunchtime.

**Comment by neftaly** [comment]
I think we'll have to make CORS issues a part if the `onerror` handler of the XHR section, as it'll be triggered whenever they're faulty on the client-side anyway. The fact that it isn't already is a quirk of the server-sidr XHR emulator. I'll go into more detail with another PR soon.

**Comment by fmarier** [comment]
That `onerror` handler was causing double responses, that's why I had to remove it.

**Comment by fmarier** [comment]
Now at almost 93% test coverage :D

**Comment by neftaly** [comment]
Code coverage is a way of measuring self-worth :P

**Comment by fmarier** [comment]
Haha. Is it worth more than raw number of commits? ;)

**Comment by fmarier** [comment]
The 404 URL now matches the other one.

**Comment by fmarier** [comment]
@neftaly good to go?

**Comment by neftaly** [comment]
+R

**Comment by fmarier** [comment]
Ta!

**Pull request merged**
