### PR TITLE
Fix HTML validation errors

### LINKED ISSUE #105: Fix HTML validation errors
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.srihash.org%2F

You could add [grunt-html](https://github.com/jzaefferer/grunt-html) to test locally in the future.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #105.

Only a warning is left now about that invalid integrity.

### CODE REVIEW

**Comment by XhmikosR** [comment]
So @mozfreddyb: should I add `grunt-html` for automated HTML validation testing?

**Comment by mozfreddyb** [comment]
Let's discuss grunt-html in its own pull request. I'd want @fmarier's opinion.

**Comment by XhmikosR** [comment]
Actually, it will be trickier to add it; grunt-html lints files so I'm not sure how to use it with nodemon.

**Comment by XhmikosR** [comment]
BTW, it seems the files on the server are cached or something?

**Comment by mozfreddyb** [comment]
I don't know how srihash.org is deployed. Would have to ask @fmarier for that as well ;)

**Comment by XhmikosR** [comment]
It seems to me it's deployed directly from the repo. But it doesn't get the latest changes for some reason.

Also, I notice poor performance from the server https://gtmetrix.com/reports/www.srihash.org/QbOjw2rB

**Comment by fmarier** [comment]
> It seems to me it's deployed directly from the repo.

That's right. It's on Heroku and it has hooks on this Github repo.

**Comment by XhmikosR** [comment]
@fmarier: any idea why performance is so bad?

**Comment by fmarier** [comment]
> @fmarier: any idea why performance is so bad?

What part of that status page are you worried about? The page load time?

Performance seems to be quite reasonable for me whenever I use it...

**Comment by XhmikosR** [comment]
For one I see the font being loaded 3 or even 4 times.

The page load time seems so big for such a simple page with no JavaScript. There's a huge waiting time which makes me think the server is very slow in responding.

See [this](https://gtmetrix.com/reports/www.srihash.org/87hQSijB) for example.

The page should load in less than 0.5s so something doesn't go right :/

On a side note, you should add Expires headers.

**Comment by fmarier** [comment]
Yeah, maybe we should just remove the font entirely. It's not that useful.

**Comment by XhmikosR** [comment]
Any suggestions what font to use then?

`'Helvetica Neue', Helvetica, Arial, sans-serif`?

**Comment by fmarier** [comment]
> Any suggestions what font to use then?

Personally, I would just leave it blank and use the browser's default.

**Pull request merged**
