### PR TITLE
input: specify `spellcheck="false"`

### PR DESCRIPTION
**Pull request by XhmikosR**
This doesn't seem to be a part of any spec but it does prevent Chrome from spellchecking the URL.

@mozfreddyb I only tested Chrome on Windows. I'm not sure how other browsers/OS'es may behave like Safari or macOS.

### CODE REVIEW

**Comment by mozfreddyb** [comment]
That's interesting!

Does spellcheck disable suggestions, e.g., for known URLs?
How does spellcheck generally interact with `type=input`?

**Comment by mozfreddyb** [comment]
> This doesn't seem to be a part of any spec but it does prevent Chrome from spellchecking the URL.

Well, it _is_ in the [HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#spelling-and-grammar-checking)

**Comment by XhmikosR** [comment]
It doesn't seem to affect anything else apart from setting spellchecking to false.

> 
> 
> > This doesn't seem to be a part of any spec but it does prevent Chrome from spellchecking the URL.
> 
> Well, it _is_ in the [HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#spelling-and-grammar-checking)

True, I was looking at the wrong mdn page :) https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Comment by XhmikosR** [comment]
So, @mozfreddyb are you OK with merging this?

**Comment by mozfreddyb** [comment]
> Does spellcheck disable suggestions, e.g., for known URLs?

curious what spellcheck means for a type=url field. 
It seems mostly unspecified, so let's merge and find out.

**Pull request merged**
