### PR TITLE
Switch to GitHub Actions CI.

### LINKED ISSUE #310: Switch to GitHub Actions
I have a branch already https://github.com/mozilla/srihash.org/compare/xmr-gh-actions

We just need it enabled for the repo.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #310 

TODO before merge:

- [ ] Remove Travis CI from repo apps/integrations/hooks
- [ ] Adapt branch protection rules

### CODE REVIEW

**Comment by mozfreddyb** [comment]
FWIW, this is still pending GitHub enabling the extension for this repo.
"Your GitHub Actions beta invitation will be arriving soon."

As mentioned previously, this needs green-lighting from the owner of the mozilla github organization.

**Comment by XhmikosR** [comment]
GitHub Actions registration is instant now, there's no waiting.

**Comment by mozfreddyb** [comment]
> GitHub Actions registration is instant now, there's no waiting.

Looking at e.g., https://github.com/mozilla/srihash.org/pull/327/checks it says " Your GitHub Actions beta invitation will be arriving soon. ".

Maybe this is different for repos that are not private?

**Comment by XhmikosR** [comment]
I swear I saw this on a tweet from GH, that registrations are instant, but maybe they changed something again.

**Comment by XhmikosR** [comment]
@mozfreddyb can you check the repo settings -> Actions? Maybe you need to enable it there?

**Comment by mozfreddyb** [comment]
image

There is no "actions" tab, still.

**Comment by XhmikosR** [comment]
Maybe someone has disabled them on the organization level?

**Comment by neftaly** [comment]
"This option is disabled for all repositories in the Mozilla organization. Contact an organization owner to enable this option."

Screenshot_2020-02-01

**Comment by XhmikosR** [comment]
@neftaly yeah that's how it is since the beginning.

**Comment by mozfreddyb** [comment]
This reads to me as if we [can't use GitHub Actions](https://wiki.mozilla.org/GitHub#GitHub_Actions). It's nothing I would be able to push for, especially since this is a side project that is very far away from my dayjob and the critical path of Firefox working well :)

**Comment by XhmikosR** [comment]
Well, I understand that, but Travis CI is clearly broken.

**Pull request closed without merging**
