### PR TITLE
Ignore the order-alphabetical CSSLint rule.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by fmarier** [comment]
Is there a good reason we should ignore this lint rule?

As far as I know, that rule exists to make CSS more compressible under gzip & friends.

**Comment by XhmikosR** [comment]
BTW my plan was to switch to Stylelint eventually.

**Comment by XhmikosR** [comment]
So, I'd say just merge this as it is for now, and we can improve things when we switch to stylelint which is a much better solution.

**Comment by fmarier** [comment]
I'd rather not disable this rule since I think it's a good one.

Not opposed to switching how the CSS is done, but in a way, merging this pull request as-is would be going against where we want to end up.

**Comment by XhmikosR** [comment]
The thing is that 1. CSS Lint is unmaintained and 2. the rule doesn't break the build as it should.

I still suggest that you merge this as is, and I'll make the switch to stylelint after my PRs are merged.

**Comment by fmarier** [comment]
If that rule is not breaking the build, is there any point in disabling it?

**Comment by XhmikosR** [comment]
There's no point in having it either ;)

Like I said, CSS Lint is unmaintained. This just makes sure we don't get any warnings.

Everything will be much better after the stylelint switch.

**Pull request merged**
