### PR TITLE
Switch to xo for linting.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is blocked due to #215. I can disable the check if you want to move on with this @mozfreddyb.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Only thing I don't know how to enforce without losing the modules checks is `strict`.

**Comment by mozfreddyb** [comment]
I'm a big fan of eslint. Why use xo? :)

**Comment by XhmikosR** [comment]
I'm a fan of course but since xo is just a wrapper around eslint with
tighter rules etc we are on the same boat

**Comment by mozfreddyb** [comment]
afaiu the main benefit of xo is that it's opinionated and if you take their config you have less work. But given that we don't adopt their whole config, we have just one more indirection to worry about.

That concerns me.
I think it would only make sense to switch to xo if we adopted their style completely.

**Comment by XhmikosR** [comment]
But we do adhere to the same style, minus a few rules. I personally prefer this approach because it covers way more stuff and it's simpler to add it than us doing this "manually".

**Pull request closed without merging**
