### PR TITLE
Production release

### PR DESCRIPTION
**Pull request by XhmikosR**
I'll wait a bit in case we have further vulnerabilities fixes soon

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mozfreddyb do you have any ideas why Travis CI doesn't fire up? That's why I personally want #310...

**Comment by XhmikosR** [comment]
I will just deploy it @mozfreddyb

**Comment by mozfreddyb** [comment]
Thanks you! I had a similar issue with travis CI not starting last week - not sure if related or not. So, I figured closing/reopening the PR would help... Though not sure if it did, because now I can't see the status here anymore ;-)

**Comment by XhmikosR** [comment]
Nope, it didn't help :/

It seems the payload is delivered (https://travis-ci.org/github/mozilla/srihash.org/builds/667207720) but the status is not reflected on GitHub.

**Pull request merged**
