### PR TITLE
Add in link to caniuse.com to SRI. Fixes: #6

### PR DESCRIPTION
**Pull request by jonathanKingston**
Fixes issue: #6

### CODE REVIEW

**Comment by fmarier** [comment]
Thanks!

Do you know what we need to do in order to get `caniuse.com` to show that SRI is supported in Firefox for Android?

**Comment by jonathanKingston** [comment]
@fmarier it's managed by https://github.com/Fyrd/caniuse/blob/master/features-json/subresource-integrity.json I can submit a PR there too.

**Comment by fmarier** [comment]
@jonathanKingston great. it was added in 43 on there as well.

**Comment by jonathanKingston** [comment]
@fmarier cool MDN is wrong then will update there also :+1: thanks

**Comment by jonathanKingston** [comment]
Ah wait read it wrong sorry. :grin:

**Pull request merged**
