### PR TITLE
Add sitemap plugin and robots.txt file

### PR DESCRIPTION
**Pull request by XhmikosR**
This should be merged after #180 to avoid conflicts.

### CODE REVIEW

**Comment by fmarier** [comment]
I don't think we want to exclude all pages from robots. They should ideally index this site.

What's the purpose of hapi-sitemap?

**Comment by XhmikosR** [comment]
@fmarier It doesn't exclude them. It actually instructs them to include everything :)

**Comment by fmarier** [comment]
> It doesn't exclude them. It actually instructs them to include everything :)

Oh, you're right, I totally misread that!

**Comment by fmarier** [comment]
So why do we need the sitemap plugin? What does it do?

**Comment by XhmikosR** [comment]
It's a common SEO practice to have a sitemap.xml and a robots.txt. In our case here, not much, but it certainly doesn't hurt having it :)

**Pull request merged**
