### PR TITLE
Switch to Node.js 12.

### PR DESCRIPTION
**Pull request by XhmikosR**
Personally I'm using Node.js 12.x for months and it seems quite stable plus all the improvements (perf etc).

### CODE REVIEW

**Comment by mozfreddyb** [comment]
Hm, interesting. Nodejs is still in preview. I'd rather like us to track stable rather than a preview release, so the expectation for breakage are lower.

**Comment by XhmikosR** [comment]
Node.js 12 is the active LTS https://nodejs.org/en/about/releases/

**Comment by mozfreddyb** [comment]
AHA! Wikipedia is wrong then. Let's do this :)

**Comment by mozfreddyb** [comment]
AHA! Wikipedia is wrong then. Let's do this :)

**Comment by XhmikosR** [comment]
See my EDIT :)

**Comment by mozfreddyb** [comment]
Maybe "CURRENT" is enough, though. You decide.

**Comment by XhmikosR** [comment]
We can wait a little more, no problem. But the performance improvement is pretty nice :)

**Pull request merged**
