### PR TITLE
Merge with neftaly:development

### PR DESCRIPTION
**Pull request by neftaly**
Hokay... this is the über-pull. You can do your talk, I can think about writing one, and the isomorphic JS interface can finally begin to rear its ugly head!

### CODE REVIEW

**Comment by fmarier** [comment]
Alright, that's all I had. That is one big PR, thanks so much for resolving almost all of the open issues!

Much appreciated!

**Comment by neftaly** [comment]
Dammit... I did the rebase and fixed everything, but apparently if you `git rebase --continue` without committing any changes, it disappears that commit from history, and merges it into the next commit.

**Comment by fmarier** [comment]
As long as you don't push your branch, you should still have the un-rebased one as `origin/development`.

So you can create a new branch based on that using:

    git branch development2 origin/development

**Comment by fmarier** [comment]
You can also create a new branch based on the top commit ID before rebasing:

    git branch development3 764ff18

**Comment by neftaly** [comment]
Thanks, luckily I created a local backup branch before rebasing/pushing.

**Comment by neftaly** [comment]
@fmarier can you please take a look? Note the addition of 68aa58d.

**Comment by neftaly** [comment]
After this is merged, can you please update the "How can I generate Integrity hashes?" example script in `templates/index.html`.

**Comment by neftaly** [comment]
Milestone!

**Pull request closed without merging**
