### PR TITLE
test/generateElement.js: use https://maps.googleapis.com/maps/api/js

### PR DESCRIPTION
**Pull request by XhmikosR**
I'm open to suggestions BTW. I just don't want to even try to load tracking domains anymore :)

### CODE REVIEW

**Comment by mozfreddyb** [comment]
Don't we want to test against a URL that returns a JS file?

**Comment by XhmikosR** [comment]
Yup, that's why I said I'm open to suggestions :)

I just want to change this because tracking and also gets blocked on my network by default, so tests fail for me locally.

**Comment by XhmikosR** [comment]
@mozfreddyb how about https://maps.googleapis.com/maps/api/js?

**Comment by mozfreddyb** [comment]
> @mozfreddyb how about https://maps.googleapis.com/maps/api/js?

:+1:

**Pull request merged**
