### PR TITLE
Use XHR for fetchResource (fix #8, #9)

### LINKED ISSUE #8: Return an error when the URL returns a non-200 status code
In particular, we should return an error when the URL returns a `404` status code, but also for anything that's not a `200`.

Of course, we should follow redirects, as per #9.

### PR DESCRIPTION
**Pull request by fmarier**
Replace isEligible with eligibility.

@neftaly first part, can you double-check?

### CODE REVIEW

**Comment by fmarier** [comment]
Actually, I think I found a small problem... will add a small fix to it.

**Comment by fmarier** [comment]
Ok, fixed.

**Comment by neftaly** [comment]
:+1:

**Comment by neftaly** [comment]
You beat me at clicking the "merge" button... you maniac!

**Pull request merged**
