### PR TITLE
Improve coverage

### PR DESCRIPTION
**Pull request by XhmikosR**
**Don't merge yet!**

@fmarier: I'm trying to improve the coverage. I can't find a test URL for these 2 cases:

1. returns `.forbidden`
2. is a CDN and is not in our secureHosts.json

### CODE REVIEW

**Comment by XhmikosR** [comment]
For 2. I found a random one from ckeditor. Not sure if it's wise/ethical to use that, so I'm open to suggestions. :)

**Comment by mozfreddyb** [comment]
Sorry this has been sitting in the review queue for so long. But, to be clear, it would be much easier to get these approved if you started opening an issue and finding consensus before you submit the patch.
That being said:

* :+1: to the patch that replaces equal with strictequal etc.
* The tests for `genereteElement()` look good, but I'd rather have a test file somewhere under our control, so other websites can't pull the carpet down below us. Alternatively, we test a bit less end-to-end and synthesize the HTTP resonse?

**Comment by mozfreddyb** [comment]
Maybe split out the strict assert commit into its own PR and we can merge that already

**Comment by XhmikosR** [comment]
Sec, I rebased and pushed an npm vuln fix too here. Just don't squash this.

**Comment by XhmikosR** [comment]
I can split the patches if you insist, just lazy to do it :P

**Comment by XhmikosR** [comment]
>    * The tests for `genereteElement()` look good, but I'd rather have a test file somewhere under our control, so other websites can't pull the carpet down below us. Alternatively, we test a bit less end-to-end and synthesize the HTTP resonse?

We already depend on 3rd-party CDNs for tests hence why I went with this approach. But I can change it to anything if you have a suggestion.

**Comment by mozfreddyb** [comment]
Oops. Right. Then let's take it and do a follow-up to detangle in the long term. Don't have a great suggestion though :slightly_frowning_face:

**Pull request merged**
