### PR TITLE
Add Babel & convert to ES6

### PR DESCRIPTION
**Pull request by neftaly**
Babel is needed to compile JSX for the React interface.
It supports ES6 out-of-the-box, so I've updated the syntax in helpers.

I also replaced the OO `bind` with partial application for `processResource` (e13bdfe).

### CODE REVIEW

**Comment by neftaly** [comment]
If you want to have a chat about how Babe/transpilation works, feel free to give me a call :)

Coincidentally there's a nodejs meetup happening tonight, which I believe will be discussing it. Real close to your office, too -- you're welcome to attend!

**Comment by fmarier** [comment]
Ah, I see. In that case, can you split the ES6 into a different PR?

I'm ok with merging the babel stuff if it's a dependency of your react work, but we should talk more about ES6.

**Comment by neftaly** [comment]
Cool. Is it OK if I leave the `bind` fix here, or should I make another PR?

**Comment by fmarier** [comment]
Yeah that fix is fine.

**Comment by jonathanKingston** [comment]
Hey has there been any progress on this, it looks like the work is all submitted?

**Comment by fmarier** [comment]
This patch has bitrotted, let's close it until the react UI is ready to merge.

**Pull request closed without merging**
