### PR TITLE
Add page description.

### LINKED ISSUE #258: Add a meta description

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #258

### CODE REVIEW

**Comment by mozfreddyb** [comment]
should have something about *checking* the resources (for content-type and cors maybe)?

**Comment by XhmikosR** [comment]
I think that would be too technical, maybe?

Not that my description is perfect, but you know :)

**Comment by mozfreddyb** [comment]
Maybe just "Subresource Integrity (SRI) Hash Generator"?

**Comment by XhmikosR** [comment]
The thing is we need this to be a little longer, hence why I added the other stuff.

**Pull request merged**
