### PR TITLE
Detect if the browser supports integrity via JavaScript.

### PR DESCRIPTION
**Pull request by XhmikosR**
Some notes.

1. This will obviously fail when JavaScript is disabled. Nothing will be shown in that case since the div is empty.
2. `addEventListener` is IE9+. But it seems other browsers aren't supported so I just went with less code.
3. Alternatively we could have the fail badge in index.html and replace its classes. Or the other way around.

Let me know your thoughts. I feel this way results in much cleaner code.

### CODE REVIEW

**Comment by mozfreddyb** [comment]
I *personally* prefer the css solution

**Comment by fmarier** [comment]
> I personally prefer the css solution

Me too. It kinda feels weird to need to run scripts just to detect this when we don't have to.

**Comment by XhmikosR** [comment]
I can change it so that we only inject stuff when it fails.

Too bad you guys aren't in favor of this; I certainly can't see how `foo* bar *` and having 3 stylesheets is cleaner than this.

**Comment by fmarier** [comment]
> I certainly can't see how foo* bar * and having 3 stylesheets is cleaner than this.

Because we don't use JavaScript anywhere on the site, we can have a CSP policy that disables all scripts. Also, it means that users of NoScript don't have to whitelist `srihash.org`.

**Comment by XhmikosR** [comment]
That I understand. I wish there was another way to do this, but I don't know any.

I guess it's a matter of choice from you guys so feel free to close this.

**Pull request closed without merging**
