### PR TITLE
Optimize SVGs. 

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by mozfreddyb** [comment]
My SVG knowledge is limited, so I don't know whether the metadata is relevant for any consumers :man_shrugging:

**Comment by XhmikosR** [comment]
They are not needed for displaying as you can see from the preview :)

**Comment by XhmikosR** [comment]
BTW I explicitly kept the license header, 'cause I thought you wouldn't want it removed.

**Comment by mozfreddyb** [comment]
Yeah, I was wondering about the ` <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/>`bits.
I'm also wondering what the `<g id="layer1" transform="matrix(0.9765625,0,0,1.0003126,0,-988.92906)">` is doing.

The patched svg and the current svg differ, as the current seems to have a white margin when viewed alone.

**Comment by XhmikosR** [comment]
Those are fine AFAICT. The transform has been converted to a path.

**Comment by XhmikosR** [comment]
https://github.com/mozilla/srihash.org/blob/0d913c17f8099cfc16cda84e1a26cd5e99d80356/public/badge/fail.svg

https://github.com/mozilla/srihash.org/blob/f1281298a93b2145afa28676eedb609654dd2d6d/public/badge/fail.svg

**Comment by mozfreddyb** [comment]
:man_shrugging: :slightly_smiling_face:

**Pull request merged**
