### PR TITLE
Link to Chrome and Firefox downloads (fixes #31)

### LINKED ISSUE #31: Add instructions on getting an SRI-supported browser to test with
Given the recent hash format change, neither my [initial patch](https://bugzilla.mozilla.org/show_bug.cgi?id=992096) nor the Chrome Dev channel have support for the spec.

Once it's possible to test this feature using these browsers, we should add instructions on how to do it.

### PR DESCRIPTION
**Pull request by fmarier**
@neftaly r?

### CODE REVIEW

**Comment by neftaly** [comment]
I'm not really a fan of how `arrayShuffle` mutates the original array - how do you feel about just using https://www.npmjs.com/package/array-shuffle? It has tests and everything :)

**Comment by fmarier** [comment]
Yeah, I don't know how I feel about adding yet another dependency just to shuffle two things :)

Maybe we do it like this for now and revisit if we end up using that function more?

(rebased onto latest master)

**Comment by mozfreddyb** [comment]
Why overcomplicate this? ;D
You can just use `Math.round(Math.random()*2)` to get an array index. Use this to `splice` off the first one, then use the other.

**Comment by fmarier** [comment]
> Why overcomplicate this? ;D
> You can just use Math.round(Math.random()*2) to get an array index. Use this to splice off the first one, then use the other.

I'm hoping other browsers will join us ;)

**Comment by fmarier** [comment]
@neftaly I'd like to merge this tonight so that it's up to date in time for tomorrow's article on `hacks.mozilla.org`. Any objections?

**Comment by neftaly** [comment]
Francois, I'm beginning to severely question your commitment to bikeshedding!

Make it clone the array first (not mutate the original array), and I'll provide my +R :)

**Comment by fmarier** [comment]
@neftaly there you go, I even added a test to prove it works :-P

**Comment by neftaly** [comment]
LGTM :)
As an aside, what would be the best way to test something like this IRL? Statistical comparison with a bunch of repetitions? Dummy Math.random?

**Comment by fmarier** [comment]
> As an aside, what would be the best way to test something like this IRL? Statistical comparison with a bunch of repetitions? Dummy Math.random?

I used a dummy `Math.random` in [node-libravatar](https://github.com/fmarier/node-libravatar/blob/master/tests/federation.js#L96-L144) after @chilts suggested that approach to me.

**Pull request merged**
