### PR TITLE
Add "generate" route which returns JSON

### PR DESCRIPTION
**Pull request by fmarier**
This will be used once we have a fancy JS front-end.

### CODE REVIEW

**Comment by neftaly** [comment]
There are a bunch of doublequotes that should be singlequotes (as they're object literals, not JSON). R.E. 4db3b1d

**Comment by fmarier** [comment]
Ah yeah, I'll fix that.

**Comment by fmarier** [comment]
I think I've got them now.

**Comment by neftaly** [comment]
Aside from the doublequote in line 97, everything looks fine.
I wonder if it's worth using singlequotes in the `options` object literal in `generateElement`? It's about to be wiped out, anyway...

**Comment by fmarier** [comment]
Fix for line 97.

**Pull request merged**
