### PR TITLE
Add a hash function <select> choice

### PR DESCRIPTION
**Pull request by dsprenkels**
This patch adds a `<select>` button to the form, with which the user can select which hash function they would like to use for the SRI tag.

### CODE REVIEW

**Comment by mozfreddyb** [comment]
Thanks @dsprenkels, this seems great from looking at the code.
Can you do rebase and do a test deployment on your github pages for me to preview?

**Comment by dsprenkels** [comment]
@mozfreddyb See <https://dsprenkels.github.io/srihash.org/>.

**Comment by mozfreddyb** [comment]
Thanks!

Testing with a SHA-512 breaks the layout for me (tested with https://code.jquery.com/jquery-3.4.1.min.js, but any URL should reproduce):

image


I think you want to add `word-break: break-all;` to the style of `#sriSnippet.is-active` -- or rather, figure out why the existing `word-break: break-all` that we have don't match here and move it somewhere more reasonable.

(and there's a merge conflict, which you may or may not run into if #452 lands before you)

**Comment by mozfreddyb** [comment]
aaaand I found another issue, that needs resolving :)

Currently, the website looks quite nice and usable on mobile (and although I agree that it's questionable whether someone really wants to compute SRI attributes on mobile) - it would be nice if the input row (text input, select button, hash) were not so small and in one horizontal row when on mobile.

Maybe it could be split into "input - newline - buttons", but I honestly don't know what the most reasonable solution in CSS looks like :-)

**Comment by dsprenkels** [comment]
@mozfreddyb Thanks for the review. I'll try to look into it this week. :)

**Comment by mozfreddyb** [comment]
@dsprenkels are you still working on this? don't worry if you aren't, just checking in..

**Comment by dsprenkels** [comment]
@mozfreddyb I had completely forgotten that I was working on this. :P

I'll try to look into it again soon. If I don't get around to doing it, anybody should feel free to finish my work. :)

**Comment by kota-yata** [comment]
Is the implementation like this?
https://kota-yata.github.io/srihash.org/
スクリーンショット 2021-03-26 1 25 42

**Comment by mozfreddyb** [comment]
@kota-yata that looks about right. Do you want to "steal" this PR?

**Comment by kota-yata** [comment]
Yes. should I create a new PR?

**Comment by kota-yata** [comment]
@mozfreddyb Yes. should I create a new PR?

**Comment by mozfreddyb** [comment]
@kota-yata yeah, please do :)

**Comment by dsprenkels** [comment]
Closed in favour of #497.

**Pull request closed without merging**
