### PR TITLE
Update sri-toolbox

### LINKED ISSUE #38: "Content-type" header is passed directly into result
We need to parse the content-type header before generating the SRI attribute.

```
request.result = {
    'content-type': 'text/javascript; charset=UTF-8'
   ...
}
sri.generateHash (request.result);
//=> "<script src="file.js" integrity="type:text/javascript; charset=UTF-8 sha256-..."></script>"
```

This is a security issue; both XSS and the ability to spoof hashes. 

```
request.result = {
    'content-type': 'text/javascript sha512-fAkEhAsH'
   ...
}
sri.generateHash (request.result);
//=> "<script src="file.js" integrity="type:text/javascript sha512-fAkEhAsH sha256-rEaLhAsH"></script>"
```

I'm mad at myself for not noticing this earlier.

### PR DESCRIPTION
**Pull request by neftaly**
Closes #38

### CODE REVIEW

**Comment by neftaly** [comment]
@fmarier I put a "a-zA-Z0-9_\/\-" whitelist in neftaly/sri-toolbox. There isn't yet a super robust way to test the fix in mozilla/srihash.org, but there is a new test in sri-toolbox.

You can try it manually on "mozilla.org/humans.txt".

**Comment by fmarier** [comment]
BTW, you're the [top contributor](https://github.com/mozilla/srihash.org/graphs/contributors) to this project now, congratulations! :)

**Comment by neftaly** [comment]
Yay! Can I fire you and sellout the project to the highest bidder? :P

**Comment by fmarier** [comment]
Haha, just like a proper Bay Area startup ;)

**Comment by fmarier** [comment]
What's the commit I should be looking at in sri-toolbox?

**Comment by neftaly** [comment]
I buzzed you with a line comment

**Pull request merged**
