### PR TITLE
Sandbox the iframe (fix #49)

### LINKED ISSUE #49: Sandbox the iframe
We currently use an iframe to return the results of the backend lookup. Since it doesn't need to have any scripts in it, we should sandbox it.

Note: it's already constrained by CSP, but there's no reason not to sandbox it too.

### PR DESCRIPTION
**Pull request by fmarier**

### CODE REVIEW

**Comment by fmarier** [comment]
@neftaly r?

**Comment by neftaly** [comment]
Do you think it should have `allow-same-origin`, so that it can load the fonts in `style.css`?

**Comment by fmarier** [comment]
BTW, I'm not sure whether or not I told you already, but these are the Mozilla codes for reviews:

- `r?`: *can you review this?*
- `r+`: *looks good to me*
- `r-`: *please change/fix these things first*

**Comment by fmarier** [comment]
You don't have to use them, but I thought maybe you didn't know what I meant by `r?` :)

**Comment by neftaly** [comment]
"I just spent 4 days writing this PR, but I'm too lazy to type out an entire word" :P

**Comment by fmarier** [comment]
> Do you think it should have allow-same-origin, so that it can load the fonts in style.css?

It seems to load fine (I've just hacked this on production, you can test it there). I'm not sure CSP is supposed to see these as different origins.

**Comment by fmarier** [comment]
Hm, actually, it does in Chrome, maybe it's a Fx bug...

**Comment by neftaly** [comment]
Aurora:
```
13:54:03.303 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://srihash.org/OpenSans-Light.woff. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>
13:54:03.304 downloadable font: download failed (font-family: "Open Sans" style:normal weight:300 stretch:normal src index:2): bad URI or cross-site access not allowed source: https://srihash.org/OpenSans-Light.woff1 style.css:5:12

```
Chrome stable:
```
Refused to load the stylesheet 'https://srihash.org/style.css' because it violates the following Content Security Policy directive: "style-src 'self'".
```

**Comment by neftaly** [comment]
I didn't know that stylesheets follow CORS

**Comment by fmarier** [comment]
Fixed.

I'll file a Fx bug tomorrow.

**Comment by neftaly** [comment]
* `r++`: *looks good to me, and I commend your efforts*

**Pull request merged**
