### PR TITLE
Handle unrecognized content-types

### LINKED ISSUE #42: Handle presentation for unknown file formats differently
At the moment we currently fallback to `js` for unrecognized content-types, and output a `<script>` tag:
```html
<script src="hello.pdf" integrity="type:application/pdf sha256-ZZZZ"></script>
```

I propose that for unrecognized content-types we generate only the attribute itself:
 ```
integrity="type:application/pdf sha256-ZZZZ"
```

In the future, we can differentiate the output even further:
> Please insert the following attribute into your element:
> `integrity="type:application/pdf sha256-ZZZZ"`

### PR DESCRIPTION
**Pull request by neftaly**
Closes #42

### CODE REVIEW

**Comment by neftaly** [comment]
@fmarier

**Comment by fmarier** [comment]
Looks good to me.

BTW, we are live! https://srihash.org/

**Comment by neftaly** [comment]
Yay! We should set up full CI (automatic uploads) via Travis, the WWW prefix and vendor HSTS (if you haven't already) :D

**Comment by fmarier** [comment]
It's on a temporary (my own), so it's fully manual right now :)

HSTS was supposed to be enabled, I'm not sure why it's not, I'll have a look at my Apache config...

**Comment by neftaly** [comment]
Oh, it's serving HSTS headers correctly; I meant <https://hstspreload.appspot.com/>

**Comment by fmarier** [comment]
Ah I see, it's probably not worth spamming the preload list for such a low-security site :) Especially since the grand plan is to turn it into a fully client-side app.

**Comment by neftaly** [comment]
Either you submit it, or I will ;)

**Comment by fmarier** [comment]
Let's wait until it's more popular and more publicly launched (i.e. on proper infrastructure).

**Comment by neftaly** [comment]
:+1:

**Pull request merged**
