### PR TITLE
Add a favicon.ico.

### LINKED ISSUE #119: Add a favicon
Maybe we could use one of the badges, the success one?

### PR DESCRIPTION
**Pull request by XhmikosR**
It's just the pass.svg made into a favicon.ico with 16x16 and 32x32 icons.

Fixes #119.

ss

BTW if there was an API to detect if a browser supports SRI hashes, we could change this dynamically.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Forgot to mention, I didn't add the `link` tag since all browsers look for favicon.ico in root. I can add it if you want.

**Comment by fmarier** [comment]
> I didn't add the link tag since all browsers look for favicon.ico in the server root. I can add it if you want.

I think it would be nice to have the `link` tag as well.

**Comment by mozfreddyb** [comment]
@XhmikosR Add the `<link>` tag and we'll merge.

**Comment by XhmikosR** [comment]
@mozfreddyb @fmarier: I added it but it certainly is redundant.

**Comment by fmarier** [comment]
Again, thanks for all of the great pull requests :)

**Pull request merged**
