### PR TITLE
Improved linting

### PR DESCRIPTION
**Pull request by neftaly**

### CODE REVIEW

**Comment by neftaly** [comment]
@fmarier

**Comment by fmarier** [comment]
Please re-order the commits (a trivial `git rebase -i`) so that the one that fixes the code style issues is first.

The reason behind this is that it's preferrable to never break the tests at any point in the commit history. Otherwise things like `git bisect` don't work very well.

So for example, if you introduce a new test, introduce the code that makes it pass in the same commit, or in a previous commit, not the other way around.

**Comment by neftaly** [comment]
Oh sure, I didn't know you could do that. Just re-order the lines on the rebase manifest?

**Comment by fmarier** [comment]
That new order looks good.

**Pull request merged**
