### PR TITLE
Add bad caching directives

### PR DESCRIPTION
**Pull request by neftaly**
The real purpose of this is to move the cache issue checker from an imperative style to a declarative style. That said, I'd appreciate if you could also confirm the validity of `badCacheDirectives` (I was working from a spec).

Is it worth writing more tests for the extra directives?

### CODE REVIEW

**Comment by neftaly** [comment]
@fmarier

**Comment by fmarier** [comment]
Which spec are you working from?

These two values are based on the implementation (which checks for only these two) and that is in turn based on [advice from one of our networking engineers](https://bugzilla.mozilla.org/show_bug.cgi?id=992096#c24).

**Comment by neftaly** [comment]
I was just reading whatever I could get my hands on, regarding caching.

I'm happy to defer to their advice (as mentioned, my main goal is fixing this one bit of imperative code in order to better match the declarative style of the rest of the program). However, [this section](http://tools.ietf.org/html/rfc7234#section-7.1.3) in the referenced RFC lists a whole mess of "do not cache" directives.

**Comment by neftaly** [comment]
Is the PR OK if I change this?

```javascript
var badCacheDirectives = [
  'no-store',
  'private',
];
```

**Comment by fmarier** [comment]
Until we need to check more values, I'd propose we keep the current one-liner.

**Pull request closed without merging**
