### PR TITLE
Gracefully deal with 404s (fix #50)

### LINKED ISSUE #50: 404s cause the application to crash
If you put `http://feeding.cloud.geek.nz/rss.xml` in the search box (an invalid URL that returns a 404), the application crash with the following stack trace:

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Not a string or buffer
    at Hash.update (crypto.js:209:17)
    at digest (/home/francois/devel/srihash.org/node_modules/sri-toolbox/generate.js:28:14)
    at /home/francois/devel/srihash.org/node_modules/sri-toolbox/generate.js:48:42
    at Array.map (native)
    at hashes (/home/francois/devel/srihash.org/node_modules/sri-toolbox/generate.js:47:14)
    at Object.main [as generate] (/home/francois/devel/srihash.org/node_modules/sri-toolbox/generate.js:56:32)
    at /home/francois/devel/srihash.org/lib/helpers.js:172:32
    at XMLHttpRequest.processResource (/home/francois/devel/srihash.org/lib/helpers.js:86:12)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/francois/devel/srihash.org/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/francois/devel/srihash.org/node_modules/xhr2/lib/xhr2.js:340:12)
```

### PR DESCRIPTION
**Pull request by fmarier**

### CODE REVIEW

**Comment by fmarier** [comment]
Just added a test to make sure we don't break this in the future.

**Comment by fmarier** [comment]
@neftaly are you ok to merge this?

**Comment by neftaly** [comment]
I'm (finally) depreciating generateElement right now, give me a bit :)

**Comment by fmarier** [comment]
In that case, let's merge these first (and fix the embarrassing bugs). Then we can rebase your improvements on top.

**Comment by fmarier** [comment]
Good comments. I've just pushed a fixed version.

**Comment by fmarier** [comment]
Weird, not sure why the test coverage decreased after making your suggested changes. But hey, can't get myself to care about 0.16% :)

**Comment by neftaly** [comment]
Looks good. Should the intentional 404 URL be a little clearer? Like `https://code.jquery.com/intentional-404.js`. Also, does this work on unknown hosts?

**Comment by fmarier** [comment]
Unknown hosts are in #63.

**Comment by neftaly** [comment]
Ok, cool

**Comment by neftaly** [comment]
Looks good, +R after Travis build :)

**Pull request merged**
