### PR TITLE
fixed stylelint issues preventing upgrade in #606

### PR DESCRIPTION
**Pull request by ethanmckean**
This should fix the issue in #606. 

The error was:
`style.css
 207:8  ✖  Expected "context" media feature range notation  media-feature-range-notation`

An explanation can be found [here](https://stylelint.io/user-guide/rules/media-feature-range-notation/#options).

### CODE REVIEW

**Comment by mozfreddyb** [comment]
Thank you for looking into it. However, it looks like this failed. In parallel #633 introduced a new version that does not require a change anymore?

**Comment by mozfreddyb** [comment]
Sigh! I guess that's still broken with the -config update in #635. The run also has some deprecation warnings. Do you think you can tackle those?

**Comment by ethanmckean** [comment]
Did not meant to close this PR - still getting used to GitHub! I believe I have this fixed and will push a change shortly.

**Comment by mozfreddyb** [comment]
Still a few things missing, Ethan:

> Deprecation warnings:
>  - The "at-rule-semicolon-space-before" rule is deprecated.
>  - The "at-rule-name-space-after" rule is deprecated.
>  - The "color-hex-case" rule is deprecated.
>  - The "declaration-block-semicolon-newline-after" rule is deprecated.
>  - The "declaration-block-semicolon-newline-before" rule is deprecated.
>  - The "declaration-block-semicolon-space-after" rule is deprecated.
>  - The "max-empty-lines" rule is deprecated.
>  - The "media-feature-parentheses-space-inside" rule is deprecated.
>  - The "media-feature-range-operator-space-after" rule is deprecated.
>  - The "media-feature-range-operator-space-before" rule is deprecated.
>  - The "number-leading-zero" rule is deprecated.
>  - The "selector-list-comma-newline-after" rule is deprecated.
>  - The "selector-list-comma-newline-before" rule is deprecated.
>  - The "selector-list-comma-space-after" rule is deprecated.
>  - The "selector-list-comma-space-before" rule is deprecated.
>  - The "selector-max-empty-lines" rule is deprecated.
>  - The "string-quotes" rule is deprecated.
>  - The "value-list-comma-newline-after" rule is deprecated.
>  - The "value-list-comma-newline-before" rule is deprecated.
>  - The "value-list-comma-space-after" rule is deprecated.
> 
> style.css
>  207:14  ✖  Unexpected whitespace before range operator  media-feature-range-operator-space-before

**Comment by ethanmckean** [comment]
That should fix it! For whatever reason 34.0.0 reintroduced the requirement for `media-feature-range-notation` so I re-added it.

**Comment by mozfreddyb** [comment]
thanks! :)

**Pull request merged**
