### PR TITLE
[WIP] Update Hapi to v18 and its plugins.

### LINKED ISSUE #212: update dependencies
Some dependencies in package.json are out of date. I thought we had used greenkeeper to stay up to date.
This bug is
- a nudge to get the dependencies updated (once)
- a reminder to investigate when greenkeeper broke, why and how to update in a more streamlined way

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #212 

Preview with `?w=1` https://github.com/mozilla/srihash.org/pull/229/files?utf8=%E2%9C%93&diff=unified&w=1.

- [x] Fix the `POST` route
- [x] See if the sitemap plugin works, currently I removed it. Doesn't seem to work with the newer Hapi.
- [ ] Convert the remaining callback-based functions to Promises
- [ ] Use `reject` in the new Promise-based functions

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mozfreddyb: do you think we should merge this as is?

**Comment by mozfreddyb** [comment]
I think this would be good to have, are you still in agreement? :-)
`npm install`ing srihash as it is, gives lots of warnings and current hapi is horribly outdated :|

**Comment by XhmikosR** [comment]
@mozfreddyb: I'm gonna update the deps on master first. Can you then make a deployment?

If all goes well I will rebase this one and we can merge it. I also want to merge #267 and #266.

**Comment by XhmikosR** [comment]
Ok, I updated to the latest scoped packages. It seems to work locally.

Also, `npm i` is clean now:

```
C:\Users\xmr\Desktop\srihash.org>npm i

> nodemon@1.19.0 postinstall C:\Users\xmr\Desktop\srihash.org\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 716 packages from 851 contributors and audited 4859 packages in 18.95s
found 0 vulnerabilities
````

**Comment by mozfreddyb** [comment]
OK, I just deployed current master and I _think_ I told heroku to always automatically deploy master from now on, assuming CI passes.

**Comment by mozfreddyb** [comment]
let's merge :)

**Comment by XhmikosR** [comment]
@mozfreddyb: did the master deployment work? Because now it throws an error.

**Comment by XhmikosR** [comment]
What is the Node.js version that runs right now on Heroku? Could be this reason hence why #267.

Regardless you only have access to the logs, so please let me know. I know for sure it works fine locally.

**Comment by mozfreddyb** [comment]
it said "deploy successful" and the page ran. maybe it reported success too early. I can see the error and I think I know how to fix.

It doesn't seem to to the right port. Heroku expects it to bind to $PORT and kills the process if it doesnt listen after 60 seconds.

**Comment by XhmikosR** [comment]
Maybe it has to do with the `host` addition? `host: 'localhost',`

**Comment by mozfreddyb** [comment]
logs are at https://paste.rs/TxM - I'm still debugging.

If you want to talk synchronously, talk to freddyb on irc.mozilla.org :)

**Comment by XhmikosR** [comment]
On which channel though? :P

**Pull request merged**
